# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: efrecon/tcl
#image: appropriate/curl

#pipelines:
#  default:
#    - step:
#        script:
#          - tar -czvf projman-0.4.5-1.tgz *
#          - curl ftp://nuk-svk.ru --user $FTP_USER:$FTP_PASS --upload-file projman-last.tgz
          
image: appropriate/curl

pipelines:
  default:
    - step:
        script:
          #- mkdir SOURCES
          - tar -czvf projman-0.4.5-1.tgz *
          #- runuser rpmbuild /usr/local/bin/docker-rpm-build.sh projman.spec
          - docker run -e VERBOSE=1 --rm --volume=$BUILD_DIR:/src --workdir=/src   jitakirin/rpmbuild projman.spec
          #- rpmbuild -r /opt/atlassian/pipelines/agent/build -ba projman.spec
          #- curl ftp://nuk-svk.ru --user $FTP_USER:$FTP_PASS --upload-file projman-0.4.5-1.tgz
#definitions: 
#  services:
#    docker: 
#      image: jitakirin/rpmbuild
#      environment: 
#        MYSQL_DATABASE: 'db'
